Bumping to HTML5 & adding device friendly meta tag
NullHypothesis/obfs4PortScan pull request #1
Opened 2019-06-03 23:43 UTC by mrphs

Because why not :)

2019-06-03 23:45 UTC, mrphs commented
But in all seriousness, this small change makes the viewing of the service page on smaller monitors and on modern devices easier.

2019-06-13 15:47 UTC, NullHypothesis requested changes
Thanks for the patch, Nima! I only have one minor suggestion. Other than that, it looks good.

2019-06-13 15:47 UTC, NullHypothesis commented on html.go
> +  <meta charset=utf-8">
There's a missing " before utf-8.

2019-08-01 04:15 UTC, mrphs commented
Ah you're right. The new github confuses me so I fixed it with a squash and forced push :)

2019-08-20 16:05 UTC, merged

2019-08-20 16:08 UTC, NullHypothesis commented
Thanks! Merged and deployed.